/* Copyright © 2005-2018 Kuali, Inc. - All Rights Reserved
 * You may use and modify this code under the terms of the Kuali, Inc.
 * Pre-Release License Agreement. You may not distribute it.
 *
 * You should have received a copy of the Kuali, Inc. Pre-Release License
 * Agreement with this file. If not, please write to license@kuali.co.
 */
package org.kuali.kra.irb.drools.rules


import org.kuali.kra.irb.actions.submit.ActionRightMapping;


rule "Rule 1 -  202/203/204/304"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('202','203','204','304'))
then	
    actionRight.setAllowed(true);
end