/* Copyright © 2005-2018 Kuali, Inc. - All Rights Reserved
 * You may use and modify this code under the terms of the Kuali, Inc.
 * Pre-Release License Agreement. You may not distribute it.
 *
 * You should have received a copy of the Kuali, Inc. Pre-Release License
 * Agreement with this file. If not, please write to license@kuali.co.
 */
package org.kuali.kra.irb.drools.rules


import org.kuali.kra.irb.actions.submit.ActionRightMapping;


rule "Rule 1 -  303 And 207/301/300/302/305/306 And 205/206/109/201/200/210/208/209 And 202/203/304/204/211/212"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303','207','301','300','302','305','306','205','206','109','201','200','210','208','209','202','203','304','204','211','212') , scheduleId != null)
then	
    actionRight.setAllowed(true);
end

rule "Rule 2 -  303 And 207/301/300/302/305/306 And 205/206/109/201/200/210/208/209 And 202/203/304/204/211/212"
salience 100
when
	actionRight : ActionRightMapping(actionTypeCode in ('303','207','301','300','302','305','306','205','206','109','201','200','210','208','209','202','203','304','204','211','212') , committeeId != null)
then	
    actionRight.setAllowed(true);;
end